### PR TITLE
Release v5.0.1 - end to end walkthrough for setup on Windows

### PR DESCRIPTION
**Pull request by Rumeister**
[Install and configure Butler-SOS on Windows.pdf](https://github.com/ptarmiganlabs/butler-sos/files/3892386/Install.and.configure.Butler-SOS.on.Windows.pdf)

### CODE REVIEW

**Comment by mountaindude** [comment]
Hi @Rumeister , thanks for the great tutorial - very nice!!

A couple of comments on it though, might help ppl avoid some issues

1. I don't think you need GCC to install Grafana on Windows... At least I have not needed that when I've installed Grafana natively on Windows server, from [this download](https://grafana.com/grafana/download?platform=windows). Or have you experienced something different, for example a need for GCC?
2. In section 3 of the PDF you refer to the download site being https://github.com/mountaindude/butler-sos.git. That's my personal fork of the main https://github.com/ptarmiganlabs/butler-sos repository. That main repo is where new releases are made etc. My own fork is likely to be full of work-in-progress stuff.

**Comment by mountaindude** [comment]
Oh, I just noted that your pull request was about the incorrect image version in the docker-compose files. That has been fixed in the [main repo](https://github.com/ptarmiganlabs/butler-sos/blob/master/src/docker-compose.yml) already, so all good there.

Still, regarding your PDF tutorial, would you like to contribute it to the main repo?
Happy to include it if so, but maybe we should fix those two things (see previous comment) first? 
I'm happy to fix them if you provide a editable doc, or you do it and submit a PR with a new PDF.

**Comment by Rumeister** [comment]
Updated the doc with those fixes. Let me know if we need any other updates/changes? Happy to send the .md and assets if you like.
[Docs.zip](https://github.com/ptarmiganlabs/butler-sos/files/4198595/Docs.zip)

**Comment by mountaindude** [comment]
Wow - this one has totally fallen between all the cracks there are... Apologies. 
I've just added the PDF into the main repo though, will push it out as a part of 5.6.1.

Cheers,
Göran

**Pull request closed without merging**
